export const styles = {
  layoutGrid: {
    display: 'grid',
    gridTemplateColumns: '320px 1fr',
    gap: 'var(--space-6)',
    alignItems: 'start',
  },
  treePanel: {
    height: '600px',
    display: 'flex',
    flexDirection: 'column',
  },
  panelTitle: {
    fontSize: 'var(--font-size-md)',
    fontWeight: '600',
    marginBottom: 'var(--space-4)',
    borderBottom: '1px solid var(--color-border)',
    paddingBottom: 'var(--space-2)',
  },
  treeContainer: {
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  detailsPanel: {
    minHeight: '600px',
  },
  detailsContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-6)',
  },
  drugHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--color-border)',
    paddingBottom: 'var(--space-4)',
  },
  drugTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-4)',
  },
  pillIconContainer: {
    width: '48px',
    height: '48px',
    backgroundColor: 'var(--color-accent-subtle)',
    borderRadius: 'var(--radius-lg)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  drugTitle: {
    fontSize: 'var(--font-size-xl)',
    fontWeight: '700',
  },
  genericName: {
    fontSize: 'var(--font-size-sm)',
    color: 'var(--color-text-secondary)',
  },
  badgeContainer: {
    display: 'flex',
    alignItems: 'center',
  },
  quickInfoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 'var(--space-4)',
  },
  infoCard: {
    backgroundColor: 'var(--color-bg-tertiary)',
    border: '1px solid var(--color-border)',
    borderRadius: 'var(--radius-md)',
    padding: 'var(--space-3) var(--space-4)',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  infoLabel: {
    fontSize: 'var(--font-size-xs)',
    color: 'var(--color-text-tertiary)',
    textTransform: 'uppercase',
    fontWeight: '600',
    letterSpacing: '0.05em',
  },
  infoValue: {
    fontSize: 'var(--font-size-sm)',
    fontWeight: '600',
    color: 'var(--color-text-primary)',
  },
  stockAlert: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-3)',
    backgroundColor: 'var(--color-danger-bg)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: 'var(--radius-md)',
    padding: 'var(--space-4)',
    fontSize: 'var(--font-size-sm)',
    color: 'var(--color-danger-light)',
  },
  sectionTitle: {
    fontSize: 'var(--font-size-base)',
    fontWeight: '600',
    marginBottom: 'var(--space-4)',
  },
  tableWrapper: {
    border: '1px solid var(--color-border)',
    borderRadius: 'var(--radius-md)',
    overflow: 'hidden',
  },
  boldCode: {
    fontFamily: 'monospace',
    fontWeight: '600',
    color: 'var(--color-text-primary)',
  },
  code: {
    fontFamily: 'monospace',
    fontSize: 'var(--font-size-xs)',
  },
  editInput: {
    width: '80px',
    padding: '4px 8px',
    height: '28px',
  },
};
